ONE-4711: pnpm migration

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -39,18 +39,18 @@ command -v watchman >/dev/null 2>&1 || {
   brew install watchman
 }
 
-# Ensure Yarn is installed
-command -v yarn >/dev/null 2>&1 || {
-  echo "This app requires Yarn package manager, but it was not found on your system."
-  echo "Installing yarn with brew..."
-  brew install yarn
+# Ensure Pnpm is installed
+command -v pnpm >/dev/null 2>&1 || {
+  echo "This app requires Pnpm package manager, but it was not found on your system."
+  echo "Installing pnpm with brew..."
+  brew install pnpm
 }
 
 # Ensure react-native-cli is installed
 command -v react-native >/dev/null 2>&1 || {
   echo "This app requires react-native-cli, but it was not found on your system."
-  echo "Installing react-native-cli globally with yarn..."
-  yarn global add react-native-cli
+  echo "Installing react-native-cli globally with pnpm..."
+  pnpm global add react-native-cli
 }
 
 # IF NEEDED: Ensure appleSimUtils is installed
@@ -77,10 +77,10 @@ command -v react-native >/dev/null 2>&1 || {
 # }
 
 echo "----------------------------------------------------------"
-echo "Installing NPM Packages with Yarn"
+echo "Installing NPM Packages with Pnpm"
 echo "----------------------------------------------------------"
 
-yarn || { echo "NPM Packages could not be installed!"; exit 1; };
+pnpm i || { echo "NPM Packages could not be installed!"; exit 1; };
 
 echo "----------------------------------------------------------"
 echo "Installing CocoaPods"
@@ -102,7 +102,7 @@ echo "----------------------------------------------------------"
 echo "Running tests to verify setup is complete"
 echo "----------------------------------------------------------"
 
-yarn test || { exit 1; }
+pnpm test || { exit 1; }
 
 echo "----------------------------------------------------------"
 echo "Setup complete!"
